# This workflow builds a Docker image for Hive using the flexible Dockerfile
# and pushes it to a container registry like Docker Hub.

name: Build and Push Hive Image

on:
  push:
    branches:
      - main
  # You can also add a workflow_dispatch trigger to run it manually
  # workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      # Use a matrix to build different versions of the image
      matrix:
        include:
          # This combination is for Hive 3.1.3, which requires the older PostgreSQL driver.
          - hive_tag: "3.1.3"
            pg_driver_version: "42.2.8"
          # This combination is for a newer, standalone Hive metastore,
          # which can use a newer PostgreSQL driver.
          - hive_tag: "standalone-metastore-4.1.0"
            pg_driver_version: "42.7.7"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Log in to Docker Hub. You'll need to set these as secrets in your repository settings.
      # DOCKERHUB_USERNAME
      # DOCKERHUB_TOKEN (a Personal Access Token)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the Docker image with the specified build arguments from the matrix.
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./Dockerfile  # Assumes the Dockerfile is in the root directory
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/hive-metastore:${{ matrix.hive_tag }}-${{ matrix.pg_driver_version }}
          build-args: |
            HIVE_IMAGE_TAG=${{ matrix.hive_tag }}
            POSTGRESQL_DRIVER_VERSION=${{ matrix.pg_driver_version }}

