# This workflow automates the process of building and pushing
# two distinct Docker images to GitHub Container Registry (ghcr.io).

name: Build Hive Images


on:
  workflow_dispatch:
  push:
    branches: [ "main", "master", "develop" ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-*'
  pull_request:
    branches: [ "main", "master", "develop" ]
  release:
    types: [published]

env:
  REGISTRY: ghcr.io


jobs:
  build-hive-313:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Hive 3.1.3 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:hive-3.1.3
          build-args: |
            HIVE_IMAGE_TAG=3.1.3
          cache-from: type=gha
          cache-to: type=gha,mode=max


  build-metastore-410:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Metastore 4.1.0 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:hive-metastore-4.1.0
          build-args: |
            HIVE_IMAGE_TAG=standalone-metastore-4.1.0
          cache-from: type=gha
          cache-to: type=gha,mode=max
